/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_idea_androiddemopartone_act_JniTestTwoActivity */

#ifndef _Included_com_example_idea_androiddemopartone_act_JniTestTwoActivity
#define _Included_com_example_idea_androiddemopartone_act_JniTestTwoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_idea_androiddemopartone_act_JniTestTwoActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_idea_androiddemopartone_act_JniTestTwoActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

