/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_idea_androiddemopartone_act_JniTestActivity */

#ifndef _Included_com_example_idea_androiddemopartone_act_JniTestActivity
#define _Included_com_example_idea_androiddemopartone_act_JniTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_idea_androiddemopartone_act_JniTestActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_idea_androiddemopartone_act_JniTestActivity_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_example_idea_androiddemopartone_act_JniTestActivity
 * Method:    getStringFromNative_second
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_idea_androiddemopartone_act_JniTestActivity_getStringFromNative_1second
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
